sm8350-common: Add DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE & Declare missing HALs
log:
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.lineage.health.IChargingControl/default (@2)
    vendor.lineage.health.IFastCharge/default (@2)
    vendor.lineage.livedisplay.IPictureAdjustment/default (@1)
    vendor.lineage.livedisplay.ISunlightEnhancement/default (@1)
    vendor.lineage.powershare.IPowerShare/default (@1)
    vendor.lineage.touch.IHighTouchPollingRate/default (@1)
    vendor.lineage.touch.ITouchscreenGesture/default (@1)

Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 6.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 6 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success

Signed-off-by: absoluten00b <whiteviolent8@gmail.com>